# Site settings
title: J. Alexander Branham
email: branham@utexas.edu
description: > # this means to ignore newlines until "baseurl:"
  "Materials for a math refresher course for incoming grad students."
exclude: ['homeworks/', 'slides/', 'pre-math-camp.Rmd']
theme: minima
