---
title: "Marginal, Joint, and Conditional Probabilities"
author: "J. Alexander Branham"
date: "Fall 2015"
header-includes: 
  - \usetheme[titleformat=smallcaps, progressbar=frametitle]{metropolis}
output: 
  beamer_presentation:
    incremental: true
    latex_engine: xelatex
classoption: aspectratio=169
---

# Marginal probability
* The $Pr$ of an event occurring:
    + $Pr(A)$
* Unconditional probability
* Probability of drawing a red card from a standard deck:
$$Pr(red) = \dfrac{1}{2}$$

# Joint probability
* The probability of both $A$ **and** $B$
    + $Pr(A, B)$
* This is the intersection  of the two sets
* $Pr(A \cap B)$
    + Probability of drawing a red card and a 4:
    + $Pr(red, 4) = \dfrac{2}{52} = \dfrac{1}{26}$

# Conditional probability
* The probability of some event happening **given** some other event having occurred
    + $Pr(A|B)$
* You've drawn a red card. What's the probability it's a four?
    + $Pr(4 | red) = \dfrac{2}{26} = \dfrac{1}{13}$

# How to convert marginal, joint, and conditional probabilities
$$
Pr(A|B) = \dfrac{Pr(A,B)}{Pr(B)}
$$
* The conditional probability is equal to the joint probability over the probability of the condition 

# Bayes' Law (Theorem)
$$
Pr(A|B) = \dfrac{Pr(B|A) Pr(A)}{Pr(B)} = \dfrac{Pr(B|A) Pr(A)}{Pr(B|A)Pr(A) + Pr(B|\neg A) Pr(\neg A)}
$$

# Bayes Example
* Police set up roadblock to randomly screen for potentially drunk drivers
* Person stopped and fails breathalyzer test
    + Test gives positive 98 percent of the time when person is drunk
    + Also gives positive 5 percent of the time when the person is actually sober 
    + We think that 1 percent of people going through the checkpoint are drunk 
* What is the probability that the man was actually drunk? 

# DWI Example
* Since he's randomly stopped, we think there is a 1 percent change he's drunk 
    + $Pr(drunk) = 0.01$
* Test accuracy:
    + $Pr(positive | drunk) = 0.98$
    + $Pr(positive | \neg drunk) = 0.05$
* Want to know:
    + $Pr(drunk | positive) = \dfrac{Pr(drunk) Pr(positive | drunk)}{Pr(positive)}$
* Everything known, except $Pr(positive)$

# $Pr(positive)$
$$
\begin{split}
Pr(positive) & = Pr(positive|drunk)Pr(drunk) \\
 & +Pr(positive|\neg drunk)Pr(\neg drunk)\\
 & = .98(.01) + .05(.99) \\
 & \approx .0593
\end{split}
$$

# $Pr(drunk | positive)$
* $Pr(drunk | positive) = \dfrac{Pr(drunk) Pr(positive | drunk)}{Pr(positive)}$
* $Pr(drunk | positive) = \dfrac{0.01(.98)}{.0593}$
* $.165$
* So there is a 16.5 percent chance that the man is drunk given that he tested positive

# Example, take two: Monty Hall
* *Let's Make a Deal* was a game show where contestants were asked to choose one of three doors (A, B, and C). Behind one is a car and behind the other two are goats 
* Once contestants chose a door, Monty would open one of the doors they *didn't* choose that had a goat behind it
* The contestant could then either stick with their original choice or switch to the unopened door 
* Does switching doors increase your probability of winning? 
    + YES! 
    + Nearly 10,000 people wrote in refusing to believe this (including 1,000 PhDs!)
    
# Bayes's solution to Monty Hall
* $Pr(A) = Pr(B) = Pr(C) = \dfrac{1}{3}$ (prior belief about where the car is)
* WLOG assume contestant picks door $A$
* WLOG assume Monty opens door $B$
* Then: $Pr(B_{Monty}|A) = \dfrac{1}{2}$ and $Pr(B_{Monty}|B=0)$ and $Pr(B_{Monty}|C) = 1$

\pause

$$Pr(B_{Monty}, A) = Pr(B_{Monty}|A)Pr(A) = \dfrac{1}{2}* \dfrac{1}{3} = \dfrac{1}{6}$$
$$Pr(B_{Monty}, B) = Pr(B_{Monty}|B)Pr(B) = 0* \dfrac{1}{3} = 0$$
$$Pr(B_{Monty}, C) = Pr(B_{Monty}|C)Pr(C) = 1* \dfrac{1}{3} = \dfrac{1}{3}$$

\pause

* Note that $Pr(B_{Monty})= Pr(B_{Monty}, A) + Pr(B_{Monty}, B) + Pr(B_{Monty}, C) = \dfrac{1}{6} + 0 + \dfrac{1}{3} = \dfrac{1}{2}$

# $Pr(A|B_{Monty})$ and $Pr(C|B_{Monty})$
* $Pr(A|B_{Monty}) = \dfrac{Pr(A)Pr(B_{Monty} |A)}{Pr(B_{Monty})} = \dfrac{ \dfrac{1}{3} * \dfrac{1}{2}}{\dfrac{1}{2}} = \dfrac{1}{3}$
* $Pr(C|B_{Monty}) = \dfrac{Pr(C)Pr(B_{Monty} |C)}{Pr(B_{Monty})} = \dfrac{ \dfrac{1}{3} * 1}{\dfrac{1}{2}} = \dfrac{2}{3}$
* So switch! 
