---
title: "Introduction to Math for Political Scientists"
author: "Day 3 Homework"
date: "Fall 2017"
output: pdf_document
---

1. Consider the following matrices:
$$
C = 
\begin{bmatrix}
1 & 3\\
5 & 6
\end{bmatrix}
E = 
\begin{bmatrix}
1 & 1 \\
0 & 1 \\
1 & 0 \\
2 & 1 \\
1 & 3 
\end{bmatrix}
F = 
\begin{bmatrix}
1 & 3 & 7 \\
2 & 1 & 4 \\
3 & 1 & 5
\end{bmatrix}
G = 
\begin{bmatrix}
5 & 3 & 2 & 4 & 1 \\
0 & 2 & 1 & 2 & 0 
\end{bmatrix}
$$
    1. Which pairs of matrices are conformable for multiplication?
    2. Perform the matrix multiplication of all the conformable pairs containing $C$.
    3. Using one of the pairs from the previous question, demonstrate that the commutative property does not hold for matrix multiplication.
    4. What would the identity matrix ($I$) for $F$ look like? 
    5. Demonstrate that $FI = IF = F$

2. Consider the following matrices: 
$$
B = 
\begin{bmatrix}
2 \\ 
3 \\
1 \\
4 
\end{bmatrix}
A = 
\begin{bmatrix}
2 & 0 & 3
\end{bmatrix}
C = 
\begin{bmatrix}
1 \\
0 \\
5
\end{bmatrix}
M = 
\begin{bmatrix}
1 & 0 & 2 \\
1 & 2 & 4 \\
2 & 3 & 2 
\end{bmatrix}
L = 
\begin{bmatrix}
2 & 3 \\
1 & 4
\end{bmatrix}
$$
Find the following:
    1. $BA'$
    2. $A'B$
    3. $A'C$
    4. $100L$
    5. $MC$

3. Consider the following matrices: 
$$
C = 
\begin{bmatrix}
1 & 3 \\
5 & 6
\end{bmatrix}
E = 
\begin{bmatrix}
1 & 1 \\
0 & 1 \\
1 & 0 \\
2 & 1 \\
1 & 3 
\end{bmatrix}
F = 
\begin{bmatrix}
1 & 3 & 7 \\
2 & 1 & 4 \\
3 & 1 & 5
\end{bmatrix}
G = 
\begin{bmatrix}
5 & 3 & 2 & 4 & 1 \\
0 & 2 & 1 & 2 & 0
\end{bmatrix}
$$
$$
X = 
\begin{bmatrix}
1 & 4 & 3 \\
2 & 2 & 2 \\
0 & 1 & 4
\end{bmatrix}
Y = 
\begin{bmatrix}
1 & 0 & 5 \\
3 & 1 & 4 \\
77 & 3 & 2 
\end{bmatrix}
Z = 
\begin{bmatrix}
1 & 0 & 1 \\
1 & 0 & 0 \\
2 & 1 & 0 
\end{bmatrix}
W = 
\begin{bmatrix}
1 & 4 \\
2 & 3
\end{bmatrix}
$$
Find the following: 
    1. The transpose of $C, E, X, Y$, and $G$
    2. $CE'$
    3. $(X + Y)'$
    4. $(CG)'$
    5. $(33W)'$

4. The `mtcars` dataset comes with R and has data about cars.
    1. You can view the beginning of the data with the `head` function. Try it with `head(mtcars)`. 
    1. What are the names of the variables in the dataset? (hint: `?names`)
    2. How many observations (rows) are in the dataset? (hint: `?dim`)
    3. What is the average miles per gallon of a car in that dataset? (hint: `mean`)
    4. What is the mean weight (`wt`) of a car?
    5. Produce a scatterplot with `wt` on the x-axis and `mpg` on the y-axis. (`plot` in base R or `geom_point` in `ggplot`)
    6. Bonus OLS problems:
        1. The `lm` is the way to run OLS in R. It will produce a line of best fit for the data. 
        2. Run the command `with(mtcars, lm(mpg~weight))`. This will tell R to run OLS with `mpg` as the dependent variable and `wt` as the predictor variable. 
        3. What is the intercept? Describe both its value as well as its subtantive intrepretation.
        4. What is the slope? Describe both its value as well as its substantive intrepretation. (hint: a one unit change in x is associated with\ldots)
        5. If you're feeling especially adventurous with R, try adding the line of best fit to the scatterplot you made above. (hint: in `ggplot`, you can do this with the `stat_smooth` command with the `method` set to `"lm"`)
        
