---
title: "Intro to Math for Political Scientists"
author: "Day 2 Homework"
date: "Fall 2017"
output: pdf_document
---

1. Find the following:
    1. $\lim_{x\to 1} 2x^2+1$
    2. $\lim_{x\to 0} \left(\frac{2x^3 - 8}{x-1}\right)$
    3. $\lim_{x\to 2}\left(\frac{x^2 + 4x + 4}{x^2-4}\right)$
    4. $\lim_{x\to -1} (x+1)^{-4}$
    5. $\lim_{x\to \infty} (x+1)^{-4}$
2. Find the first and second derivatives with respect to $x$ of the
   following functions:
    1. $f(x) = -89$
    2. $f(x) = 3x-2$
    3. $f(x) = 5x^3 - 2x^2 + 6$
3. Find the derivative (with respect to $x$) of the following
   functions:
    1. $f(x) = (4x^2+7)^{-2}$
    2. $f(x) = \frac{x^4 + 3x^{-3} + 6x - 1}{x^{-2}+2x}$
    3. $f(x) = (8x^2+3x)(x^4+2)$
4. A scholar argues that Texas's feelings for Donald Trump in the
   upcoming election can be modeled with this function:
   $$y = \beta_0 + \beta_1 x_1 + \beta_2 x_2^2 + \beta_3 x_3$$
   where $y$ represents how warmly an individual feels towards Trump,
   $x_1$ represents a voter's frequency of church attendance, $x_2$
   represents a voter's age, and $x_3$ represents their party
   identification. What is the derivative of $y$ with respect to party
   identification? What is the derivative of $y$ with respect to age? 
5. Find all the extrema of these functions, and determine whether they
   are maxima or minima:
    1. $f(x) = \frac{x^3}{3} - x$
    2. $f(x) = (x-2)^2 + 2$ 
