---
title: "Intro to Math for Political Scientists"
author: "Day 1 Homework"
date: "Fall 2015"
output: pdf_document
---

1. Simplify the following expressions as much as possible.
    1. $9(3)^3$
    2. $(2a^2)(4a^4)$
    3. $\dfrac{x^4}{x^3}$
    4. $\dfrac{1}{27b^3}^{1/3}$
    5. $y^7y^5y^6y^4$
2. Simplify the following, making the answer free of any negative exponents.
$$
(a^2b^{-1}c^{3/5})(a^{-3}b^{1/2}d^{1/4})
$$

3. Solve for $x$ in the following:
    1. $\sqrt[4]{625} = x$
    2. $\sqrt[x]{64} = 4$
    3. $log_{10}(1) = x$
    4. $log_{10}(x) = 3$
    5. $ln\left( \dfrac{1}{3^{3/2}}\right) = x$
    6. $ln(e) = x$
    7. $log_2(\dfrac{1}{8} = x$
    8. $log_x(64) = 3$
    9. $log_5(5^20) = x$
    10. $ln(e^82) = x$
    11. $e^{ln(3)} = x$

4. Take the logarithm of the following function and use the rules for logs to make it linear (additive instead of multiplicative). 
$$
y = x^2 z^3 w^4
$$

5. $e^{1-x} = x$ Solve for $x$. 

6. The concentration of alcohol in a person's blood is measurable. Suppose that the risk $R$ (as a perccentage) of having an accident while driving a car can be modeled by the following equation:
$$
R = 3e^{kx}
$$
where $x$ is the concentration of alcohol in the blood and $k$ is a constant. 
    1. Suppose that a concentration of alcohol in the blood of $0.06$ results in a 10 percent risk $(R=10)$ of an accident. Find the constant $k$ in the equation.
    2. Using this value of $k$, what is the risk if the concentration is $0.17$? 
    3. Using the same value of $k$, what concentration of alcohol corresponds to a risk of 100 percent?
    4. If the law asserts that anyone with a risk of having an accident of 15 percent may not drive, at what concentraion of alcohol in the blood should a driver be arrested for DUI? 
    
7. If you have time, it's a good idea to familiarize yourself with the [Greek alphabet](https://en.wikipedia.org/wiki/Greek_alphabet)